### PR TITLE
Fix for Issue#39 authLoginDomain should not be "Local" by default by removing the default value

### LINKED ISSUE #1: Explain what MSMB is -
Explain what MSMB is before using the acronym.

### PR DESCRIPTION
**Pull request by soodpr**
### Description
It fixes the authLoginDomain should not be "Local" by default.

### Issues Resolved

[Fixes#39](https://github.com/HewlettPackard/oneview-sdk-java/issues/39)

---
#### Check List
- [X] New functionality includes testing
- [X] New functionality has been thoroughly documented in the examples
- [ ] New functionality has been documented in the [`README.md`](https://github.com/HewlettPackard/oneview-sdk-java/blob/master/README.md) if applicable
- [X] New functionality has been documented in the [`CHANGELOG.md`](https://github.com/HewlettPackard/oneview-sdk-java/blob/master/CHANGELOG.md) if applicable
- [ ] New functionality has been documented in the [`endpoints-support.md`](https://github.com/HewlettPackard/oneview-sdk-java/blob/master/endpoints-support.md) if applicable

### CODE REVIEW

File: oneview-sdk-java-lib/src/main/java/com/hp/ov/sdk/rest/http/core/client/SDKConfiguration.java [hunk 1]
```diff
@@ -30,7 +30,7 @@
 
     private static final int DEFAULT_MESSAGE_BUS_PORT = 5671;
     private static final ApiVersion DEFAULT_API_VERSION = ApiVersion.V_300;
-    private static final String DEFAULT_DOMAIN = "LOCAL";
+    // private static final String DEFAULT_DOMAIN = "LOCAL";
```
Comment (lhsvobodaj) [inline oneview-sdk-java-lib/src/main/java/com/hp/ov/sdk/rest/http/core/client/SDKConfiguration.java]: Remove this line.

**Review by lhsvobodaj — CHANGES_REQUESTED** [review]

File: oneview-sdk-java-lib/src/main/java/com/hp/ov/sdk/rest/http/core/client/SDKConfiguration.java (hunk 1 above)
Comment (adriane-cardozo) [reply oneview-sdk-java-lib/src/main/java/com/hp/ov/sdk/rest/http/core/client/SDKConfiguration.java]: Agree, you should remove this line.

**Review by lhsvobodaj — APPROVED** [review]
